
# Minima theme settings
theme: minima
minima:
  skin: dark
  social_links:
    twitter: https://twitter.com/yourhandle
    github: https://github.com/yourhandle

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
